[package]
name = "example-clack"
version = "0.1.0"
edition = "2024"

license = "MIT OR Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
clack-plugin = { git = "https://github.com/prokopyl/clack", rev = "5deaa1be9b5af7078d75cbe54abefee12ed40f63" }
clack-extensions = { git = "https://github.com/prokopyl/clack", rev = "5deaa1be9b5af7078d75cbe54abefee12ed40f63", features = ["audio-ports", "clack-plugin", "note-ports", "params", "state"] }
clap-wrapper = { path = "../.." }