name: Validate

on: [push]
jobs:
  validate-linux:
    strategy:
      matrix:
        runner: [ubuntu-22.04]
    name: Validate (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Checkout `vst3sdk`
        shell: bash
        run: |
            git clone --depth=1 https://github.com/steinbergmedia/vst3sdk
            cd vst3sdk
            git submodule update --init base
            git submodule update --init cmake
            git submodule update --init public.sdk
            git submodule update --init pluginterfaces
            cd ..

      - name: Build `example-clap`
        shell: bash
        run: |
            CLAP_WRAPPER_VST3_SDK="$(realpath vst3sdk)" CLAP_WRAPPER_VERBOSE=1 cargo build -p example-clap
            
            # bundle vst3
            mkdir -p example-clap.vst3/Contents/x86_64-linux/
            mv target/debug/libexample_clap.so example-clap.vst3/Contents/x86_64-linux/example-clap.so
  
      - name: Upload VST3
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runner }}-vst3
          path: example-clap.vst3
          retention-days: 1

      - name: Build `vst3-validator`
        shell: bash
        run: |
            cd vst3sdk
            cmake -DSMTG_ENABLE_VSTGUI_SUPPORT=OFF -DSMTG_ENABLE_VST3_PLUGIN_EXAMPLES=OFF -DSMTG_ENABLE_VST3_HOSTING_EXAMPLES=OFF -B cmake-build 
            cmake --build cmake-build --target validator
            cd ..

      - name: Run `vst3-validator`
        shell: bash
        run: |
            "./vst3sdk/cmake-build/bin/validator" -e "./example-clap.vst3" 

  validate-windows:
    strategy:
      matrix:
        runner: [windows-2022]
    name: Validate (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Checkout `vst3sdk`
        shell: bash
        run: |
            git clone --depth=1 https://github.com/steinbergmedia/vst3sdk
            cd vst3sdk
            git submodule update --init base
            git submodule update --init cmake
            git submodule update --init public.sdk
            git submodule update --init pluginterfaces
            cd ..

      - name: Build `example-clap`
        shell: bash
        run: |
            CLAP_WRAPPER_VST3_SDK="$(realpath vst3sdk)" CLAP_WRAPPER_VERBOSE=1 cargo build -p example-clap

            # bundle vst3. we dont really have to do that as the dll file by itself can be used as a vst3, 
            # but the validator really wants it to be a vst3 bundle so we have no choice
            # for more info on directory structure, see https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/Locations+Format/Plugin+Format.html
            mkdir -p example-clap.vst3/Contents/x86_64-win/
            mv target/debug/example_clap.dll example-clap.vst3/Contents/x86_64-win/example-clap.vst3

      - name: Upload VST3
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runner }}-vst3
          path: example-clap.vst3
          retention-days: 1

      - name: Build `vst3-validator`
        shell: bash
        run: |
            cd vst3sdk
            cmake -DSMTG_ENABLE_VSTGUI_SUPPORT=OFF -DSMTG_ENABLE_VST3_PLUGIN_EXAMPLES=OFF -DSMTG_ENABLE_VST3_HOSTING_EXAMPLES=OFF -B cmake-build
            cmake --build cmake-build --target validator
            cd ..

      - name: Run `vst3-validator`
        shell: bash
        run: |
            "./vst3sdk/cmake-build/bin/Debug/validator" -e "./example-clap.vst3" 
      
  validate-macos:
    strategy:
      matrix:
        runner: [macos-13, macos-15]
    name: Validate (${{ matrix.runner }})
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Checkout `vst3sdk`
        shell: bash
        run: |
            git clone --depth=1 https://github.com/steinbergmedia/vst3sdk
            cd vst3sdk
            git submodule update --init base
            git submodule update --init cmake
            git submodule update --init public.sdk
            git submodule update --init pluginterfaces
            cd ..

      - name: Checkout `AudioUnitSDK`
        shell: bash
        run: |
            git clone --depth=1 https://github.com/apple/AudioUnitSDK 

      - name: Build `example-clap`
        shell: bash
        run: |
            CLAP_WRAPPER_VST3_SDK="$(realpath vst3sdk)" CLAP_WRAPPER_AUV2_SDK="$(realpath AudioUnitSDK)" CLAP_WRAPPER_VERBOSE=1 cargo build -p example-clap
            
            # bundle vst3 and include the Info.plist stuff
            # for more info on directory structure, see https://steinbergmedia.github.io/vst3_dev_portal/pages/Technical+Documentation/Locations+Format/Plugin+Format.html
            mkdir -p example-clap.vst3/Contents/MacOS/
            cp target/debug/libexample_clap.dylib example-clap.vst3/Contents/MacOS/example-clap
            cp examples/example-clap/Info.vst3.plist example-clap.vst3/Contents/Info.plist
            echo "BNDL????" > example-clap.vst3/Contents/PkgInfo

            # bundle auval and include the Info.plist stuff
            mkdir -p example-clap.component/Contents/MacOS/
            cp target/debug/libexample_clap.dylib example-clap.component/Contents/MacOS/example-clap
            cp examples/example-clap/Info.auv2.plist example-clap.component/Contents/Info.plist
            echo "BNDL????" > example-clap.component/Contents/PkgInfo

            # sign the plugins without an associated identity
            codesign --force --timestamp --deep -s - example-clap.vst3
            codesign --force --timestamp --deep -s - example-clap.component

      - name: Upload AUv2
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runner }}-auv2
          path: example-clap.component
          retention-days: 1

      - name: Upload VST3
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.runner }}-vst3
          path: example-clap.vst3
          retention-days: 1

      - name: Build `vst3-validator`
        shell: bash
        run: |
            cd vst3sdk
            cmake -DSMTG_ENABLE_VSTGUI_SUPPORT=OFF -DSMTG_ENABLE_VST3_PLUGIN_EXAMPLES=OFF -DSMTG_ENABLE_VST3_HOSTING_EXAMPLES=OFF -B cmake-build
            cmake --build cmake-build --target validator
            cd ..

      - name: Run `vst3-validator`
        shell: bash
        run: |
            "./vst3sdk/cmake-build/bin/validator" -e "./example-clap.vst3" 

      - name: Run `auval`
        shell: bash
        run: |
            mkdir -p ~/Library/Audio/Plug-Ins/Components
            mv example-clap.component ~/Library/Audio/Plug-Ins/Components/example-clap.component
            killall -9 AudioComponentRegistrar
            auval -a
            auval -strict -v aufx gain Mois